Pihlqvist/wallmap

src/components/Firebase/firebase.js, src/components/Places/Places.js, src/components/SignUp/SignUp.js
This fixes #22 
Changed how places requests place objects from firebase. This should now work like in the demo branch.
=> Fix places firebase request

public/index.html, src/components/Hooks/WindowSize.js, src/components/MapBox/MapBox.js, src/data/constants/dimensions.js
This fixes #18 
Mapbox should now resize itself when the screen is resized.
=> MapBox stretches to screen

src/components/AddPlace/AddPlace.js, src/components/MapBox/MapBox.js, src/components/Places/Places.js
This fixes #24 
When a user adds a place with submit query it will now be uploaded to Firebase.
The location is randomized between the available locations. We have not yet created a working geolocator.
=> Create add place functionality

public/index.html, src/components/Modal/Modal.css, src/components/Place/Place.js, src/components/Place/PlaceTable.css, src/components/Place/PlaceTable.js, src/components/Places/Places.js
PlaceTable component that displays all of the users places as a table. User can click to go to the specific place and also sort by name or date.
PlaceHook should now be used to get all the users place data. It handels the import from firebase and converts the database object to something we can work with in the app.
=> Create PlaceTable and PlaceHook

src/components/AddPlace/AddPlace.js, src/components/Place/Place.js, src/components/Place/PlaceTable.js, src/components/Places/Places.js
When adding a place the suggestion will now appear after the user types.
Location is now different, it stores coordinates and formatted name + other info.
=> Create Debounce location suggestion

public/index.html, src/components/MapBox/MapBox.css, src/components/MapBox/MapBox.js
=> create mapstyle and marker style

src/components/ForgotPassword/ForgotPassword.js, src/components/Login/Login.css, src/components/Login/Login.js, src/components/SignUp/SignUp.js, src/index.js, src/styles/Buttons.css, src/styles/Form.css, src/styles/Input.css, src/styles/Links.css
This fixes #40 
Create style for Login and Signup, contains:
- Button style
- Form style
- Link style
=> Create basic styles

src/components/AddPlace/AddPlace.js
This fixes #44 
Users can now input multiple files when creating a new place. This is stored correctly in Firebase.
=> Make it possible to upload multiple images

src/components/MapBox/MapBox.css, src/components/Places/Places.css, src/components/Profile/Profile.css
This fixes #37 
Small fix that puts the MapBox on an even z-index.
=> Fixed map marker clicking problem

src/components/AddPlace/AddPlace.js, src/components/MapBox/MapBox.js, src/components/Places/Places.js
This fixes #50 
You can now right-click on the map. This will put the AddPlace Modal on-screen and auto set the location to where you clicked.
=> Add right click to add place

src/components/Places/Places.js, src/components/Profile/Profile.js, src/components/SignUp/SignUp.js
This fixes #36 
Sets displayName when user is created. Then uses displayName for profile component.
=> Set displayName on new profiles

package-lock.json, package.json, src/components/Modal/Modal.css, src/components/Modal/Modal.js, src/components/Place/MPlaceTable.js, src/components/Places/Places.js
Changed the table to a MaterialTable component. This will give us the following features.
- searching
- filtering
- limit endless scroll
- avatar pictures (thumbnails)
It's not perfect but I was doing my head in trying to fix the table styles and features.
=> Create MaterialTable for Places

src/components/App/App.js, src/components/ForgotPassword/ForgotPassword.js
The link on the login page to forgot password now works.
=> Create ForgotPassword page

src/components/Logout/Logout.js, src/components/Profile/Profile.css, src/components/Profile/Profile.js
This fixes #62 
The profile menu now has a good style and looks better. The old was not expandable and the displayName is pretty useless.
=> Change ProfileMenu to stylized list

src/components/AddPlace/AddPlace.js, src/components/PlacesTable/PlacesTable.js, src/data/model/PlaceModel.js
This fixes #83 
The date should now be stored correctly and displayed correctly.
=> Fixed the same date problem

src/components/Profile/Profile.js
This fixes #85 
The password was changed no matter if the user put anything into that box. I changed this so that the user has to type something for it to try a password change.
I also added "New" to the label, found it more initiative.
=> Profile change setting now works well

src/index.css
This fixes #87 
Changed the input text to have stronger grey colour. This makes it stand out from the placeholder.
=> Input text now have a stronger gray

src/components/AddPlace/AddPlace.js, src/components/SuggestionInput/SuggestionInput.js
=> Remove console.logs

src/components/MapBox/MapBox.js
Fix zooming so that there is the min and max zoom for NavigationControl.
=> add min and max zoom to Mapbox  NavigationControl

src/components/Profile/Profile.js
Fixes #100. Removed the "for" attribute of label element in the Profile component.
=> remove attribute for of label in Profile component
